language: ruby

rvm:
  - 2.1
  - 2.2
  - 2.3.3 # https://github.com/travis-ci/travis-ci/issues/5361

gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_4.1.gemfile

matrix:
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/rails_5.0.gemfile

before_install:
  - gem update bundler

script: "bundle exec rake test"
